### ISSUE TITLE
Resetting a configuration entry makes the setup command crash

### ISSUE THREAD

**Issue by Alex1304** [ultimategdbot/ultimategdbot-core-plugin#2]
**To reproduce:**

- Run the setup command
- Click the reset reaction

Also reproducible by clicking the Edit reaction and resetting an individual value.

Affected version: v6.0.0-alpha2

**Comment by Alex1304** [comment]
Reopening as the fix causes a different exception, didn't happen during the first tests
```
java.lang.NullPointerException: null
	at java.base/sun.util.locale.LocaleUtils.toLowerString(LocaleUtils.java:89)
	at java.base/sun.util.locale.LanguageTag.parse(LanguageTag.java:192)
	at java.base/java.util.Locale.forLanguageTag(Locale.java:1682)
	at ultimategdbot.core@6.0.0-alpha3-SNAPSHOT/com.github.alex1304.ultimategdbot.core.database.CoreConfigData.lambda$configurator$4(CoreConfigData.java:69)
```
